### PR TITLE
Feat/reconnect

### PR DESCRIPTION
**Pull request by ProbablePrime**
This reconnects to beam channels on a disconnect.

Its been running and reconnecting to 2 beam channels all week. 

Please review.

### CODE REVIEW

**Comment by Tromino** [comment]
Had it running for a few hours, it seems it still disconnected from its own channel without reconnecting. Maybe it could be some rate limit in Beam? I'll try disabling the global chat log in its own channel, and see if it still disconnects.

**Comment by ProbablePrime** [comment]
Oh its own channel. That might be a thing. https://github.com/ProbablePrime/BeamLink-1.0/commit/b318a3a36815be5050d0d7d48d81b9add55b167f#diff-9a9569e9d73f33740eada95275da7f30R109

We check here if we are interested in the channel. That probably needs to be "if we are interested OR its streamlink_"

**Comment by Tromino** [comment]
Oh, ok. That makes sense. Are you modifying the code now?

**Comment by ProbablePrime** [comment]
Sure why not, its like a 2 second job :D

**Comment by Tromino** [comment]
Heh, ok. I was just checking if you were already pushing a quick fix.

**Comment by ProbablePrime** [comment]
Can you search your logs for "Unhandled rejection Not authenticated." I think our session is expiring after awhile. Which means we need to refresh that too.

If this is the case its a longer job thats gonna have to wait until later, I'll ask the beam guys about session expiry.

**Comment by Tromino** [comment]
Didn't see that message anywhere, though screen only goes back a few pages. I did see a point where it just reconnected to a whole bunch of channels though, if that's important at all.

**Pull request merged**
